### ISSUE TITLE
Seems not working with VS code Version: 1.85.0

### ISSUE THREAD

**Issue by chkilel** [DCsunset/vscode-modal-editor#9]
Hello,
I'm trying to use this plugin but it seems not working with VScode  Version: 1.85.0.
I installed the extension from the market and imported the helix preset but VScode keep displaying `Modal Editor: undefined key sequence: "whatever char I type"`.
Am I missing some additional configuration ?
Thanks for your help.

**Comment by DCsunset** [comment]
Hi, I believe this is the expected behaviour because this plugin doesn't come with default keybindings.

As said in the README, "To use this extension, first you need to import keybindings. You can define your own keybindings based on the tutorial. Or you can use the preset in this repository as a start point."
